ChristDDD-master/Christ3D.UI.Web/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using Christ3D.Application.Interfaces;
using Christ3D.Application.ViewModels;
using Christ3D.Domain.Core.Notifications;
using FluentValidation;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace Christ3D.UI.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderAppService _OrderAppService;
        IValidator<OrderViewModel> _validator;
        private IMemoryCache _cache;
        // 将领域通知处理程序注入Controller
        private readonly DomainNotificationHandler _notifications;

        public OrderController(IOrderAppService OrderAppService, IMemoryCache cache, INotificationHandler<DomainNotification> notifications)
        {
            _OrderAppService = OrderAppService;
            _cache = cache;
            // 强类型转换
            _notifications = (DomainNotificationHandler)notifications;
        }

        // GET: Order
        public ActionResult Index()
        {
            return View(_OrderAppService.GetAll());
        }



        // GET: Order/Create
        // 页面
        public ActionResult Create()
        {
            return View();
        }

        // POST: Order/Create
        // 方法
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderViewModel OrderViewModel)
        {
            try
            {
                //_cache.Remove("ErrorData");
                //ViewBag.ErrorData = null;
                // 视图模型验证
                if (!ModelState.IsValid)
                    return View(OrderViewModel);

                
                // 这里为了测试，手动赋值items
                OrderViewModel.Items = new List<OrderItemViewModel>() {
                    new OrderItemViewModel (){
                        Name="详情"+DateTime.Now
                    }
                };



                // 执行添加方法
                _OrderAppService.Register(OrderViewModel);

                //var errorData = _cache.Get("ErrorData");
                //if (errorData == null)

                // 是否存在消息通知
                if (!_notifications.HasNotifications())
                    ViewBag.Sucesso = "Order Registered!";

                return View(OrderViewModel);
            }
            catch (Exception e)
            {
                return View(e.Message);
            }
        }


    }
}

ChristDDD-master/Christ3D.UI.Web/ViewComponents/AlertsViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Christ3D.Domain.Core.Notifications;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace Christ3D.UI.Web.ViewComponents
{
    public class AlertsViewComponent : ViewComponent
    {
        // 缓存注入，为了收录信息（错误方法，以后会用通知，通过领域事件来替换）
        // private IMemoryCache _cache;

        // 领域通知处理程序
        private readonly DomainNotificationHandler _notifications;

        // 构造函数注入
        public AlertsViewComponent(INotificationHandler<DomainNotification> notifications)
        {
            //_cache = cache;
            _notifications = (DomainNotificationHandler)notifications;
        }


        /// <summary>
        /// Alerts 视图组件
        /// 可以异步，也可以同步，注意方法名称，同步的时候是Invoke
        /// 我写异步是为了为以后做准备
        /// </summary>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            //// 获取到缓存中的错误信息
            //var errorData = _cache.Get("ErrorData");
            //var notificacoes = await Task.Run(() => (List<string>)errorData);
            //// 遍历添加到ViewData.ModelState 中
            //notificacoes?.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c));

            // 从通知处理程序中，获取全部通知信息，并返回给前台
            var notificacoes = await Task.FromResult((_notifications.GetNotifications()));
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));

            return View();
        }
    }
}

ChristDDD-master/Christ3D.UI.Web/Views/Order/Create.cshtml
@model OrderViewModel
@{
    ViewData["Title"] = "Register new Order";
}
<h2>@ViewData["Title"]</h2>
<form asp-action="Create">
    <div class="form-horizontal">
        <hr />
        @* 将经典验证摘要替换为自定义视图组件作为标记助手 *@

        @*方式一(可用，但不推荐) @await Component.InvokeAsync("Alerts")*@

        <!-- 如果使用这个方法，请记得在_ViewImports.cshtml 中，导入@addTagHelper "*, Christ3D.UI.Web" -->
        <vc:alerts />

        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>
    </div>
</form>

ChristDDD-master/Christ3D.UI.Web/Views/Order/Index.cshtml
@model IEnumerable<OrderViewModel>
@{
    ViewData["Title"] = "Order Management";
}
<div>
    <h2>@ViewData["Title"]</h2>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull-left">
                <a asp-action="Create" class="btn btn-primary">
                    <span title="Register New" class="glyphicon glyphicon-plus-sign"></span> Register New
                </a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="panel panel-default">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
           
                <th>详情</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                 
                    <td>
                      @(item.Items)

                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" title="Edit" class="btn btn-warning">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>

                     
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>