Abp.HotelStore/host/Acme.HotelStore.Web.Host/Controllers/AccountController.cs
using Volo.Abp.AspNetCore.Mvc.Authentication;

namespace Acme.HotelStore.Controllers
{
    public class AccountController : ChallengeAccountController
    {

    }
}

Abp.HotelStore/host/Acme.HotelStore.Web.Host/Pages/Index.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;

namespace Acme.HotelStore.Pages
{
    public class IndexModel : HotelStorePageModel
    {
        public void OnGet()
        {
            
        }

        public async Task OnPostLoginAsync()
        {
            await HttpContext.ChallengeAsync("oidc");
        }
    }
}

Abp.HotelStore/host/Acme.HotelStore.Web.Host/Pages/Index.cshtml
@page
@using Acme.HotelStore.Pages
@model IndexModel
@using Microsoft.AspNetCore.Mvc.Localization
@using Acme.HotelStore.Localization
@using Volo.Abp.Users
@inject IHtmlLocalizer<HotelStoreResource> L
@inject ICurrentUser CurrentUser
<abp-card>
    <abp-card-header>Welcome</abp-card-header>
    <abp-card-body>
        @if (!CurrentUser.IsAuthenticated)
        {
            <form method="POST">
                <input type="submit" asp-page-handler="Login" value="LOGIN" class="btn btn-primary" />
            </form>
        }
        else
        {
            <strong>Claims</strong><br />
            @Html.Raw(CurrentUser.GetAllClaims().Select(c => $"{c.Type}={c.Value}").OrderBy(x => x).JoinAsString(" <br /> "))
        }
        <hr />
        <p class="text-right"><a href="https://abp.io?ref=tmpl" target="_blank">abp.io</a></p>
    </abp-card-body>
</abp-card>